AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 'm5.2xlarge'
      ImageId: 'ami-0b72821e2f351e396' # Amazon Linux 2023 AMI
      KeyName: 'ec2'
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          # Install k6
          sudo amazon-linux-extras install epel -y
          sudo yum install -y https://dl.k6.io/rpm/repo.rpm
          sudo yum install -y k6

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH access'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'

