apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesina-scenario-network-monolithic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesina-scenario-network-monolithic
  template:
    metadata:
      labels:
        app: tesina-scenario-network-monolithic
    spec:
      containers:
        - name: tesina-scenario-network-monolithic
          image: 'juliancasaburi/tesina-scenario-network-monolithic:latest'
          env:
            - name: DYNAMODB_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: dynamodb-credentials
                  key: DYNAMODB_ACCESS_KEY_ID
            - name: DYNAMODB_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dynamodb-credentials
                  key: DYNAMODB_SECRET_ACCESS_KEY
          ports:
            - containerPort: 3000
