version: '3'
services:
  app:
    image: juliancasaburi/tesina-scenario-network-monolithic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  # Load environment variables from .env file
    pull_policy: if_not_present
