apiVersion: v1
kind: Service
metadata:
  name: tesina-scenario-network-monolithic-service
spec:
  type: NodePort
  selector:
    app: tesina-scenario-network-monolithic
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
