apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesina-scenario-cpu-monolithic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesina-scenario-cpu-monolithic
  template:
    metadata:
      labels:
        app: tesina-scenario-cpu-monolithic
    spec:
      containers:
      - name: tesina-scenario-cpu-monolithic
        image: juliancasaburi/tesina-scenario-cpu-monolithic:latest
        ports:
        - containerPort: 3000