apiVersion: v1
kind: Service
metadata:
  name: tesina-scenario-cpu-monolithic-service
spec:
  selector:
    app: tesina-scenario-cpu-monolithic
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
