AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Video Re-encoding Lambda Function

Resources:

  FfmpegLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tesina-ffmpeg-lambda-layer
      Description: FFMPEG Lambda Layer
      ContentUri: s3://tesina-casaburi-ffmpeg/ffmpeg.zip
      CompatibleRuntimes:
        - nodejs20.x

  InputBucket:
    Type: AWS::S3::Bucket

  OutputBucket:
    Type: AWS::S3::Bucket

  TesinaMigrationLongRunningProcessVideoFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TesinaMigrationLongRunningProcessVideoFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  CloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudWatchLogsPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:*:*:*'
      Roles:
        - !Ref TesinaMigrationLongRunningProcessVideoFunctionRole

  ReadS3BucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ReadS3BucketPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - !Sub '${InputBucket.Arn}/*'
      Roles:
        - !Ref TesinaMigrationLongRunningProcessVideoFunctionRole

  WriteS3BucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: WriteS3BucketPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Sub '${OutputBucket.Arn}/*'
      Roles:
        - !Ref TesinaMigrationLongRunningProcessVideoFunctionRole

  TesinaMigrationLongRunningProcessVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/app.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 3008
      Timeout: 900
      EphemeralStorage:
        Size: 10240
      Events:
        FileUploadedToS3:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:*
      Role: !GetAtt TesinaMigrationLongRunningProcessVideoFunctionRole.Arn
      Layers:
        - !Ref FfmpegLambdaLayer
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucket

Outputs:
  TesinaMigrationFfmpegFunctionArn:
    Description: "ARN of the Video Reencoder Lambda Function"
    Value: !GetAtt TesinaMigrationLongRunningProcessVideoFunction.Arn
  InputBucketName:
    Description: "Input S3 Bucket"
    Value: !Ref InputBucket
  OutputBucketName:
    Description: "Output S3 Bucket"
    Value: !Ref OutputBucket
