AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template for tesina-scenario-diurnal-nocturnal Lambda function

Resources:
  TesinaMigrationScenarioDiurnalNocturnalScalingFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/handlers/app.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        TesinaMigrationScenarioIOApi:
          Type: Api
          Properties:
            Path: /tesina-migration-scenario-diurnal-nocturnal-lambda
            Method: get

Outputs:
  TesinaMigrationScenarioIOApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tesina-migration-scenario-diurnal-nocturnal-scaling-lambda/"
