AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template for scenario-2-io-bound Lambda function

Resources:
  TesinaNetworkScenarioLambda:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TesinaNetworkScenarioLambda
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S # S for string
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST # On-demand pricing
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false

  TesinaScenarioIOFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/handlers/app.handler
      Runtime: nodejs20.x
      CodeUri: .
      MemorySize: 1536
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: !GetAtt TesinaNetworkScenarioLambda.Arn
      Events:
        TesinaScenarioIOApi:
          Type: Api
          Properties:
            Path: /tesina-scenario-io-bound-lambda
            Method: get

Outputs:
  TesinaScenarioBurstyApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tesina-scenario-io-bound-lambda/"
